Adding custom role - site_capacity_manager - for T0 and T2 CERN Disks
dmwm/CMSRucio pull request #473
Opened 2023-04-18 23:57 UTC by dynamic-entropy

The script syncs custom roles for capacity managers at CERN [CMS_TIER_0_OPS group in CRIC](https://cms-cric.cern.ch/api/accounts/group/query/?json&name=CMS_TIER_0_OPS).

I have created a general outline. The function can be used as a  skeleton for such site-specific roles. If things tend to be applied more generally, we shall try to add roles for individual users who belong to a particular e-group.

Fix #468

2023-04-18 23:59 UTC, dynamic-entropy commented
This should be merged together with #465

2023-04-19 00:01 UTC, dynamic-entropy commented
Dry Run 
```
add_site_capacity_manager_role - INFO - Updating T0_CH_CERN_Disk site capacity manager accounts to jamadova,ggiraldo,hufnagel,jaeyserm,yulee,dmytro
add_site_capacity_manager_role - INFO - Updating T2_CH_CERN site capacity manager accounts to jamadova,ggiraldo,hufnagel,jaeyserm,yulee,dmytro
```

2023-04-19 14:48 UTC, ericvaandering commented
OK

2023-04-20 14:27 UTC, ericvaandering requested changes

2023-04-20 14:27 UTC, ericvaandering commented on src/policy/permission.py
> +        site_capacity_manager = site_capacity_manager.split(',')
Please don't re-use a variable like this (changing from string to list). Just put a "s" on the end. Same comment at #872

2023-04-20 14:56 UTC, dynamic-entropy commented
> Hi Eric I am making this a draft request, till we have answers to following questions:
> 
> 1. How does deletion make use of `source_for_total_space` and `source_for_used_space`?
> 2. What happens when they are not set?
> 
> Also, another commit:
> 
> * To allow to set automatic updates for `T2_CH_CERN` on and off.

Hi 
I am yet to find my answers, I will read some Reaper code. But this PR is independent of those and thus we can go ahead with merging if everything else is fine from your end.
Secondly, the decision for having a parameter to modify is also ruled out, since now tier 0 will use the SiteCapacity page like other site admins. 
https://github.com/dmwm/CMSRucio/pull/465/commits/5aba16ba631602e369db023d5b69844414c2add6

2023-04-20 15:27 UTC, ericvaandering approved these changes

2023-04-20 15:28 UTC, merged