Add Analysis Tape Recall activity
dmwm/CMSRucio pull request #802
Opened 2024-05-22 12:21 UTC by dynamic-entropy

This activity can only be used by the `crab_tape_recall` account.

For https://github.com/dmwm/CRABServer/issues/8354

2024-05-22 14:32 UTC, ericvaandering requested changes

2024-05-22 14:32 UTC, ericvaandering commented on src/policy/CMSRucioPolicy/algorithms/auto_approve.py
> +    auto_approve_activities = ['User AutoApprove', "Analysis TapeRecall"]
Please use consistent quote styles

2024-05-22 15:58 UTC, dynamic-entropy commented on src/policy/CMSRucioPolicy/algorithms/auto_approve.py
> +    auto_approve_activities = ['User AutoApprove', "Analysis TapeRecall"]
Done.

2024-05-22 16:30 UTC, ericvaandering approved these changes

2024-05-22 16:30 UTC, merged

2024-06-28 13:52 UTC, belforte commented
**note** Activity has to be `Analysis TapeRecall` not `Analysis Tape Recall`  !